In [1]:
import requests
import pandas as pd
import numpy as np

In [ ]:

from pathlib import Path
import yaml

from dynamicTasteDistortion.ioUtils import extract_experiment_configuration, load_bootstrapped_clicks, get_oracle_matrix_path, load_pickle_artifact

config_path = Path("/home/caio/dev/dynamicTasteDistortion/experiments/globo/bpr_uncalibrated.yaml")
with config_path.open("r") as f:
    cfg = yaml.safe_load(f)

config = extract_experiment_configuration(cfg)

path = get_oracle_matrix_path(config)
oracle_matrix = load_pickle_artifact(f"/home/caio/dev/dynamicTasteDistortion/{path}")

In [ ]:
from dynamicTasteDistortion.dynamicTasteDistortion.ioUtils import load_bootstrapped_clicks


bootstrapped_df = load_bootstrapped_clicks(config)

## Twitter based data

In [ ]:


url = "https://zenodo.org/records/14834749/files/2022-brazilian-president-elections.zip?download=1"
r = requests.get(url, stream=True)
with open("elections.csv.gz", "wb") as f:
    for chunk in r.iter_content(chunk_size=8192):
        f.write(chunk)

KeyboardInterrupt:

In [7]:
!unzip elections.zip

Archive:  elections.zip
  inflating: 2022-08-01-BOLSONARO NÃO TRABALHA.parquet
  inflating: 2022-08-09-NÃO VOTE EM RACISTA.parquet
  inflating: 2022-08-22-#BolsonaroNoJN.parquet
  inflating: 2022-08-22-#Eleicoes2022.parquet
  inflating: 2022-08-22-#ForaBolsonaro.parquet
  inflating: 2022-08-22-#GloboLixo.parquet
  inflating: 2022-08-25-BOBO DA CORTE.parquet
  inflating: 2022-08-25-Faz o L.parquet
  inflating: 2022-08-25-#LADRAONOJN.parquet
  inflating: 2022-08-28-#DebateNaBand.parquet
  inflating: 2022-09-23-DINHEIRO VIVO.parquet
  inflating: 2022-09-23-Faltam 9.parquet
  inflating: 2022-09-23-SÓ CIRO VENCE LULA.parquet
  inflating: 2022-09-24-BOLSONARO CORRUPTO.parquet
  inflating: 2022-09-24-#DebateNoSBT.parquet
  inflating: 2022-09-24-MEU VOTO NÃO ANISTIA BANDIDO.parquet
  inflating: 2022-09-25-#EsseÉMeuVoto.parquet
  inflating: 2022-09-25-Faltam 7.parquet
  inflating: 2022-09-25-#LulaNo1ºTurno.parquet
  inflating: 2022-09-26-AGORA É LULA.parquet
  inflating: 2022-09-26-Bolsonaro 31%.parquet
  inflating: 2022-09-26-#BrasilDaEsperança.parquet
  inflating: 2022-09-26-BRASIL RESISTE.parquet
  inflating: 2022-09-26-#BrasilVota22.parquet
  inflating: 2022-09-26-#CiroManifestoANacao.parquet
  inflating: 2022-09-26-#CiroNoFlow.parquet
  inflating: 2022-09-26-Faltam 6.parquet
  inflating: 2022-09-26-Lula 48%.parquet
  inflating: 2022-09-26-#LulaNo1ºTurno.parquet
  inflating: 2022-09-26-LULA NO PRIMEIRO TURNO.parquet
  inflating: 2022-09-26-#TiraGomes.parquet
  inflating: 2022-09-28-#DebateNaGlobo.parquet
  inflating: 2022-10-30-#BolsonaroReeleito2️⃣2️⃣.parquet
  inflating: 2022-10-30-#LulaPresidente1️⃣3️⃣.parquet
  inflating: 2022-10-30-Polícia Rodoviária Federal.parquet
  inflating: 2022-10-31-Apertei 13.parquet
  inflating: 2022-10-31-DEIXEM O NORDESTE VOTAR.parquet
  inflating: 2022-10-31-#LulaPresidente1️⃣3️⃣.parquet
  inflating: 2022-11-04-400 BILHÕES.parquet
  inflating: 2022-11-04-BOLSONARO QUEBROU O BRASIL.parquet
  inflating: 2022-11-04-JAIR QUEBROU O BRASIL.parquet
  inflating: 2022-11-04-Rombo de 400.parquet
  inflating: 2022-11-06-NÓS VENCEMOS.parquet
  inflating: 2022-11-14-BOLSONARO NÃO TRABALHA.parquet
  inflating: 2022-11-14-#STFVergonhaMundial.parquet
  inflating: 2022-11-15-PERDEU MANÉ.parquet
  inflating: 2022-11-16-PERDEU MANÉ.parquet
  inflating: 2022-11-17-BOLSONARO LADRÃO.parquet
  inflating: 2022-11-17-ORÇAMENTO SECRETO NÃO.parquet
  inflating: 2022-11-18-APOIO LULA.parquet
  inflating: 2022-11-18-#Caminhoneiros.parquet
  inflating: 2022-11-18-QG DO GOLPE.parquet
  inflating: 2022-11-19-BRAGA NETO NA CADEIA.parquet
  inflating: 2022-11-19-RENUNCIA BOLSONARO.parquet
  inflating: 2022-11-22-Bolsonaro 51%.parquet
  inflating: 2022-11-22-#BolsonaroReeleito.parquet
  inflating: 2022-11-22-O LULA TÁ ELEITO.parquet
  inflating: 2022-11-23-Alexandre de Morais.parquet
  inflating: 2022-11-23-Artigo 142.parquet
  inflating: 2022-11-23-Deu 22.parquet
  inflating: 2022-11-23-É 22.parquet
  inflating: 2022-11-23-EU AUTORIZO.parquet
  inflating: 2022-11-23-Faz o 22.parquet
  inflating: 2022-11-23-Xandão.parquet
  inflating: 2022-11-24-#EuAutorizoPresidente.parquet
  inflating: 2022-11-28-Eduardo Bolsonaro.parquet
  inflating: 2022-11-29-Eduardo Bolsonaro.parquet
  inflating: 2022-11-30-Bananinha.parquet
  inflating: 2022-11-30-Eduardo Bolsonaro.parquet
  inflating: 2022-11-30-HAARP.parquet
  inflating: 2022-11-30-JAIR SAQUEOU O BRASIL.parquet
  inflating: 2022-11-30-Paquita da Ditadura.parquet
  inflating: 2022-12-02-ORÇAMENTO SECRETO NÃO.parquet
  inflating: 2022-12-06-CAPES.parquet
  inflating: 2022-12-06-#PagueMinhaBolsa.parquet
  inflating: 2022-12-07-CAPES.parquet
  inflating: 2022-12-07-ORÇAMENTO SECRETO NÃO.parquet
  inflating: 2022-12-07-#PagueMinhaBolsa.parquet
  inflating: 2022-12-08-BOLSONARO INIMIGO DA EDUCAÇÃO.parquet
  inflating: 2022-12-11-DIPLOMAÇÃO DO LULA.parquet
  inflating: 2022-12-11-Votei 22.parquet
  inflating: 2022-12-12-Armação.parquet
  inflating: 2022-12-12-bolsonaristas.parquet
  inflating: 2022-12-12-Brasília.parquet
  inflating: 2022-12-12-Cacique.parquet
  inflating: 2022-12-12-Capitólio.parquet
  inflating: 2022-12-12-#DiplomacaoDoLula.parquet
  inflating: 2022-12-12-Índio.parquet
  inflating: 2022-12-12-Infiltrados.parquet
  inflating: 2022-12-12-#LulaEoBrasilSubindoARampa.parquet
  inflating: 2022-12-12-LULA PRESIDENTE.parquet
  inflating: 2022-12-12-Manifestantes.parquet
  inflating: 2022-12-12-NÓS VENCEMOS.parquet
  inflating: 2022-12-12-Polícia Federal.parquet
  inflating: 2022-12-13-Bolsonaristas.parquet
  inflating: 2022-12-13-Fora Bolsonaro.parquet
  inflating: 2022-12-13-Infiltrados.parquet
  inflating: 2022-12-13-Patriotas.parquet
  inflating: 2022-12-13-Terroristas.parquet
  inflating: 2022-12-14-Faz o L.parquet
  inflating: 2022-12-29-Faltam 72.parquet
  inflating: 2022-12-30-ACABOU BOLSONARO.parquet
  inflating: 2022-12-30-JAIR EMBORA.parquet
  inflating: 2022-12-30-Lula.parquet

In [8]:
import pandas as pd

df = pd.read_parquet("2022-08-22-#Eleicoes2022.parquet")
df

,created_at,tweet_id,tweet_content,user,user_info,has_mention,mentions,is_reply,reply_to,is_quote,quoted_from,is_retweet,retweeted_from,hashtags
0,2022-08-25 02:58:30,1562635500669640704,O partido de Bolsonaro pediu ao TSE a exclusão...,PedroCorra10,"{'id': 3307001661, 'name': 'PHC', 'description...",False,None,False,None,False,None,True,"{'user': 'choquei', 'user_id': 953378142198161...",['#Eleições2022']
1,2022-08-25 02:58:21,1562635465186213888,Imagina evocar a imagem do rompimento de uma b...,eipaulorossi,"{'id': 92979491, 'name': '👑 Paulo Rossi 1️⃣3️⃣...",False,None,False,None,False,None,True,"{'user': 'jnascim', 'user_id': 34779125, 'twee...",['#Eleições2022']
2,2022-08-25 02:57:53,1562635346642235394,#Eleicoes2022 \n\nJamais esqueceremos.\n#ForaB...,MarioFiIho8869,"{'id': 54760625, 'name': 'Tashi Delek 🇵🇸⬛️', '...",False,None,False,None,False,None,True,"{'user': 'Mirelacastreis', 'user_id': 34304936...","['#Eleicoes2022', '#ForaBolsonaroVagabundo', '..."
3,2022-08-25 02:57:17,1562635194607489024,"🚨URGENTE: Jair Bolsonaro, candidato à reeleiçã...",renat1nh00,"{'id': 1337805436112822273, 'name': 'Cr7', 'de...",False,None,False,None,False,None,True,"{'user': 'choquei', 'user_id': 953378142198161...",['#Eleições2022']
4,2022-08-25 02:56:57,1562635110276800513,O partido de Bolsonaro pediu ao TSE a exclusão...,ofernandohalls,"{'id': 760896776715005952, 'name': 'Fernando H...",False,None,False,None,False,None,True,"{'user': 'choquei', 'user_id': 953378142198161...",['#Eleições2022']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76487,2022-08-22 03:01:40,1561549134309597185,#Eleições2022 Beneficiários de recursos dos 25...,jnascim,"{'id': 34779125, 'name': 'Jeff Nascimento', 'd...",False,None,False,None,True,"{'user': 'jnascim', 'user_id': 34779125, 'twee...",False,None,['#Eleições2022']
76488,2022-08-22 03:01:30,1561549093423415296,Só aqui que você sabe de tudo que acontece nas...,AquarelaTV,"{'id': 1384306177350127623, 'name': 'AquarelaT...",False,None,False,None,False,None,False,None,"['#Eleicoes2022', '#AquarelaTV']"
76489,2022-08-22 03:00:37,1561548869133115396,Lula e Haddad= sinônimos de destruição. \n#Ele...,opolemico,"{'id': 1398308665925550085, 'name': 'Souza', '...",False,None,False,None,False,None,False,None,"['#Eleicoes2022', '#BolsonaroReeleito']"
76490,2022-08-22 03:00:32,1561548849763737602,Envelheceu rápido demais esse Twitter ehn?! #E...,Ketley,"{'id': 15286894, 'name': 'Ketley 💉🧚🏾\u200d♀️⭐'...",False,None,False,None,True,"{'user': 'ponciosarah', 'user_id': 3614125649,...",False,None,['#Eleicoes2022']
76491,2022-08-22 03:00:01,1561548717567741953,Faltam 41 dias para o 1º turno das #Eleicoes20...,ContadorQueda,"{'id': 1478471834026885125, 'name': 'Contagem ...",False,None,False,None,False,None,False,None,['#Eleicoes2022']

In [14]:
df2 = pd.read_parquet("2022-09-25-Faltam 7.parquet")
df2

,created_at,tweet_id,tweet_content,user,user_info,has_mention,native_mentions,retweet_mentions,is_reply,reply_to,is_quote,quoted_from,is_retweet,retweeted_from,hashtags
0,Sun Sep 25 11:02:10 +0000 2022,1573991243486461953,"No próximo domingo, nesta hora, estaremos nos ...",LulaOficial,"{'name': 'Lula 13', 'id': 2670726740, 'descrip...",False,None,None,False,None,False,None,False,None,None
1,Sun Sep 25 18:40:27 +0000 2022,1574106575513554946,"Chegou a hora da virada! A hora é agora, pesso...",MarceloFreixo,"{'name': 'Marcelo Freixo 40', 'id': 45870897, ...",True,"[{'user': 'LulaOficial', 'user_id': 2670726740}]",None,False,None,False,None,False,None,"['#Freixo40', '#AHoraÉAgora']"
2,Sun Sep 25 12:37:37 +0000 2022,1574015264915685378,Faltam 7 DIAS para o Brasil votar 13.\n\nNo pr...,updatecharts,"{'name': 'UpdateCharts', 'id': 582230335, 'des...",False,None,None,False,None,False,None,False,None,None
3,Sun Sep 25 23:59:57 +0000 2022,1574186980136701953,"No próximo domingo, nesta hora, estaremos nos ...",VenancioBarros4,"{'name': 'Venancio 💉 🐊 🚩🚩🚩🌵', 'id': 1164286892...",False,None,None,False,None,False,None,True,"{'user': 'LulaOficial', 'user_id': 2670726740,...",None
4,Sun Sep 25 23:59:56 +0000 2022,1574186974272925697,São Paulo nesse momento.\n\nFaltam 7 dias para...,Dr_Paulo_Cruz,"{'name': 'Paulo Cesar Cruz', 'id': 15190805562...",True,None,"[{'user': 'jairbolsonaro', 'user_id': 128372940}]",False,None,False,None,True,"{'user': 'FlviaLeo16', 'user_id': 147037019924...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2483,Thu Sep 22 11:48:40 +0000 2022,1572915780152442881,"Olá, pessoal! Tudo bom? Só passando para lembr...",oieusouorhuan,"{'name': 'Rhuan ⚓🕯️🧭⛪', 'id': 8900092262271344...",False,None,None,False,None,False,None,True,"{'user': 'TarginoJadson', 'user_id': 134447266...",None
2484,Thu Sep 22 11:27:19 +0000 2022,1572910411070189568,Os que acham que na sexta-feira ficarei na fre...,Cal_Ipanema,"{'name': 'Cal Gomes', 'id': 167467319, 'descri...",False,None,None,False,None,False,None,False,None,None
2485,Thu Sep 22 11:18:52 +0000 2022,1572908282485907456,faltam 7 dias https://t.co/VQCBJqo1qQ,gabi_elasilvaa,"{'name': '🤠gauchinha_amarela🤠', 'id': 11902406...",False,None,None,False,None,True,"{'user': 'gabi_elasilvaa', 'user_id': 11902406...",False,None,None
2486,Thu Sep 22 11:12:36 +0000 2022,1572906705494900737,Dia: 7\n\nFaltam: 64 dias. 🇧🇷 https://t.co/4MP...,lu1zcifer,"{'name': 'russo 🇵🇹', 'id': 4136125768, 'descri...",False,None,None,False,None,False,None,True,"{'user': 'regressiva_copa', 'user_id': 1568701...",None
2487,Thu Sep 22 10:59:55 +0000 2022,1572903512740335616,"Faltam 1 semana!! \n= 7 dias, 168 horas, 10080...",lorrainyjesuss,"{'name': '⚖️🦋👑 Loly surtando É HOJEEEEEE💜🤙🏾', ...",False,None,None,False,None,False,None,False,None,None

In [12]:
df[df["is_reply"] == True].iloc[0]["tweet_content"]

'@GaucheenAvant Fake news! ACMNeto lidera com folga! \n#Eleicoes2022'

In [6]:
pd.read_csv("elections.csv.gz")

BadGzipFile: Not a gzipped file (b'PK')

In [4]:
pd.read_csv("example.csv.gz")

,id_str,user.id_str,timestamp_ms,retweeted_status.id_str,quoted_status.id_str,in_reply_to_status_id_str,botscore
0,2325814490,1736687930,1535641715955,NaN,NaN,NaN,0.10
1,6842033492,1863741662,1535641716918,5.942107e+09,NaN,NaN,0.42
2,7061372474,3708875295,1535641717106,9.741995e+09,NaN,NaN,0.32
3,6837188333,254597744,1535641717560,9.278839e+09,NaN,NaN,0.33
4,8325420843,9088192393,1535641717918,1.855054e+09,NaN,NaN,0.84
...,...,...,...,...,...,...,...
106735,5566028553,7331123236,1535673599641,9.943527e+09,NaN,NaN,0.11
106736,9139186156,9946982479,1535673599828,NaN,NaN,NaN,0.05
106737,4546202457,2705886063,1535673599840,9.543164e+09,NaN,NaN,0.03
106738,2212789201,6922525988,1535673599900,5.306074e+09,NaN,NaN,0.07
106739,1210485000,7261873553,1535673599851,NaN,NaN,5.693310e+09,0.11

## Ebnerd dataset

In [4]:

url = "https://ebnerd-dataset.s3.eu-west-1.amazonaws.com/ebnerd_demo.zip"
r = requests.get(url, stream=True)
with open("ebnerd.zip", "wb") as f:
    for chunk in r.iter_content(chunk_size=8192):
        f.write(chunk)

In [5]:
!unzip ebnerd.zip

Archive:  ebnerd.zip
  inflating: articles.parquet
  inflating: __MACOSX/._articles.parquet
   creating: train/
  inflating: __MACOSX/._train
  inflating: train/history.parquet
  inflating: __MACOSX/train/._history.parquet
  inflating: train/behaviors.parquet
  inflating: __MACOSX/train/._behaviors.parquet
   creating: validation/
  inflating: __MACOSX/._validation
  inflating: validation/history.parquet
  inflating: __MACOSX/validation/._history.parquet
  inflating: validation/behaviors.parquet
  inflating: __MACOSX/validation/._behaviors.parquet

In [3]:
articles = pd.read_parquet("articles.parquet")

In [4]:
articles.columns

Index(['article_id', 'title', 'subtitle', 'last_modified_time', 'premium',
       'body', 'published_time', 'image_ids', 'article_type', 'url',
       'ner_clusters', 'entity_groups', 'topics', 'category', 'subcategory',
       'category_str', 'total_inviews', 'total_pageviews', 'total_read_time',
       'sentiment_score', 'sentiment_label'],
      dtype='object')

In [ ]:
1+1

In [ ]:
articles["topics"].drop_duplicates()

AttributeError: 'Series' object has no attribute 'distinct'

## MIND dataset

In [7]:
news = pd.read_csv("mind_data/MINDsmall_train/news.tsv", sep="\t", header=None, names=["news_id", "category", "subcategory", "title", "abstract", "url", "title_entities", "abstract_entities"])

In [9]:
news["category"].drop_duplicates()

0            lifestyle
1               health
2                 news
5               sports
6              weather
8        entertainment
11               autos
17              travel
26        foodanddrink
32                  tv
49             finance
56              movies
76               video
134              music
929               kids
8215        middleeast
46861     northamerica
Name: category, dtype: object

In [14]:
bla = sorted(news["subcategory"].drop_duplicates().tolist())
for subcat in bla:
    print(subcat)

ads-latingrammys
ads-lung-health
advice
animals
autosbuying
autoscartech
autosclassics
autoscompact
autosenthusiasts
autoshybrids
autoslosangeles
autosluxury
autosmidsize
autosmotorcycles
autosnews
autosownership
autospassenger
autosresearch
autosresearchguides
autosreview
autossema
autossports
autossuvs
autostokyo
autostrucks
autosvans
autosvideonew
autosvideos
awards
awardstyle
baseball
baseball_mlb
baseball_mlb_videos
basketball_nba
basketball_nba_videos
basketball_ncaa
basketball_ncaa_videos
basketball_wnba
beverages
boxing
boxing-mma
cardio
career-news
causes
causes-animals
causes-disaster-relief
causes-environment
causes-food-insecurity
causes-green-living
causes-military-appreciation
causes-poverty
celebhub
celebrity
celebritynews
cma-awards
cocktails
comedy
company-news
cooking
cookingschool
downtime
elections-2020-us
empowering-the-planet
entertainment-books
entertainment-celebrity
entertainmentmusic
entertainmenttv
factcheck
finance-auto-insurance
finance-billstopay
finance-career
finance-career-education
finance-companies
finance-credit
finance-education
finance-healthcare
finance-home-loans
finance-homesandpropertysection
finance-insidetheticker
finance-insurance
finance-mutual-funds
finance-real-estate
finance-retirement
finance-savemoney
finance-saving-investing
finance-small-business
finance-startinvesting
finance-taxes
finance-technology
finance-top-stocks
finance-video
financenews
fitness
foodanddrink
foodnews
foodrecipes
foodtips
football_ncaa
football_ncaa_videos
football_nfl
football_nfl_videos
fun
games
gaming
golf
golfvideos
halloween
health-cancer
health-news
healthagingwell
healthnews
healthyliving
holidays
hollywood
humor
icehockey_nhl
indepth
internationaltravel
lifestyle
lifestyle-news-feature
lifestyle-wedding
lifestylebeauty
lifestylebuzz
lifestylecareer
lifestylecelebstyle
lifestylecleaningandorganizing
lifestyledecor
lifestyledidyouknow
lifestylediy
lifestylefamily
lifestylefamilyandrelationships
lifestylefashion
lifestylehomeandgarden
lifestylehoroscope
lifestylehoroscopefish
lifestylelovesex
lifestylemarriage
lifestylemindandsoul
lifestyleparenting
lifestylepets
lifestylepetsanimals
lifestylerelationships
lifestyleroyals
lifestyleshopping
lifestyleshoppinghomegarden
lifestylesmartliving
lifestylestyle
lifestylevideo
lifestyleweddings
lifestylewhatshot
markets
medical
mentalhealth
middleeast-top-stories
mma
mmaufc
more_sports
movienews
movies-awards
movies-celebrity
movies-gallery
movies-oscars
movievideo
music-awards
music-celebrity
music-gallery
music-grammys
music-reviews
musicnews
musicvideos
narendramodi_opinion
news
newsbusiness
newscrime
newselection2020
newsfactcheck
newsgoodnews
newsnational
newsoffbeat
newsopinion
newsother
newsphotos
newspolitics
newsrealestate
newsscience
newsscienceandtechnology
newstrends
newstvmedia
newsus
newsvideo
newsweather
newsworld
newsworldpolitics
northamerica-video
nutrition
olympics-videos
othersports
outdoors
people-places
peopleandplaces
personalfinance
photos
popculture
pregnancyparenting
quickandeasy
racing
recipes
relationships
restaurantsandnews
retirement
reviews
science
seasonal
shop-all
shop-apparel
shop-books-movies-tv
shop-holidays
shop-home-goods
soccer
soccer_bund
soccer_epl
soccer_mls
spendingandborrowing
sports
sports_news
strength
technologyinvesting
tennis
tennis_intl
tipsandtricks
topnews
travel
travel-adventure-travel
travel-points-rewards
travel-videos
travelarticle
travelnews
traveltips
traveltripideas
traveltrivia
tunedin
tv
tv-celebrity
tv-gallery
tv-golden-globes
tv-golden-globes-video
tv-recaps
tv-reviews
tvnews
tvvideos
ustravel
video
videos
viral
voices
watch
weatherfullscreenmaps
weathertopstories
weight-loss
weightloss
wellness
wines
wonder
yearinoffbeatgoodnews

In [24]:
a = "caio"


a.rfind("i")

2

In [63]:
from dynamicTasteDistortion.dataset_loader import download

In [ ]:
url = "https://www.kaggle.com/api/v1/datasets/download/gspmoreira/news-portal-user-interactions-by-globocom"
download(url, "temporario_globo")

Downloading file...
Criando o diretorio temporario_globo_v2?
Downloading...

HTTPError: HTTP Error 404: Not Found

In [30]:
noticias = news[
    news["category"] == "news"
]["subcategory"].drop_duplicates().tolist()


for n in sorted(noticias):
    print(n)

causes
causes-disaster-relief
causes-environment
causes-military-appreciation
causes-poverty
elections-2020-us
empowering-the-planet
factcheck
indepth
narendramodi_opinion
newsbusiness
newscrime
newselection2020
newsfactcheck
newsgoodnews
newsnational
newsoffbeat
newsopinion
newsother
newsphotos
newspolitics
newsrealestate
newsscience
newsscienceandtechnology
newstvmedia
newsus
newsvideo
newsweather
newsworld
newsworldpolitics
personalfinance
photos
yearinoffbeatgoodnews

In [8]:
news

,news_id,category,subcategory,title,abstract,url,title_entities,abstract_entities
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."
3,N53526,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",https://assets.msn.com/labs/mind/AACk2N6.html,[],"[{""Label"": ""National Basketball Association"", ..."
4,N38324,health,medical,"How to Get Rid of Skin Tags, According to a De...","They seem harmless, but there's a very good re...",https://assets.msn.com/labs/mind/AAAKEkt.html,"[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI...","[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI..."
...,...,...,...,...,...,...,...,...
51277,N16909,weather,weathertopstories,"Adapting, Learning And Soul Searching: Reflect...",Woolsey Fire Anniversary: A community is forev...,https://assets.msn.com/labs/mind/BBWzQJK.html,"[{""Label"": ""Woolsey Fire"", ""Type"": ""N"", ""Wikid...","[{""Label"": ""Woolsey Fire"", ""Type"": ""N"", ""Wikid..."
51278,N47585,lifestyle,lifestylefamily,Family says 13-year-old Broadway star died fro...,NaN,https://assets.msn.com/labs/mind/BBWzQYV.html,"[{""Label"": ""Broadway theatre"", ""Type"": ""F"", ""W...",[]
51279,N7482,sports,more_sports,St. Dominic soccer player tries to kick cancer...,"Sometimes, what happens on the sidelines can b...",https://assets.msn.com/labs/mind/BBWzQnK.html,[],[]
51280,N34418,sports,soccer_epl,How the Sounders won MLS Cup,"Mark, Jeremiah and Casey were so excited they ...",https://assets.msn.com/labs/mind/BBWzQuK.html,"[{""Label"": ""MLS Cup"", ""Type"": ""U"", ""WikidataId...",[]
51281,N44276,autos,autossports,Best Sports Car Deals for October,NaN,https://assets.msn.com/labs/mind/BBy5rVe.html,"[{""Label"": ""Peugeot RCZ"", ""Type"": ""V"", ""Wikida...",[]

## Globo dataset

In [14]:
pd.read_csv("dynamicTasteDistortion/artifacts/model/globo_1m_n_users=1000_avg_time_diff.csv").user.nunique()

1000

In [30]:
oralcke_globo = pd.read_pickle("dynamicTasteDistortion/data/simulation/globo_1m_n_users=1000_oracle.pkl")

In [31]:
oralcke_globo.user.min(), oralcke_globo.user.max()

(0, 999)

In [32]:
oralcke_globo.item.min(), oralcke_globo.item.max()

(0, 14852)

In [29]:
oralcke_globo["item"]

0              21
1              94
2             111
3             130
4             139
            ...
14853289    14848
14853290    14849
14853291    14850
14853292    14851
14853293    14852
Name: item, Length: 14853294, dtype: object

In [23]:
oralcke_globo

         user   item  rating genres
0         968     21       1  [399]
1         856     94       1  [331]
2         802    111       1  [375]
3         526    130       1  [442]
4          69    139       1  [249]
...       ...    ...     ...    ...
14853289  999  14848       0  [225]
14853290  999  14849       0  [136]
14853291  999  14850       0  [138]
14853292  999  14851       0  [196]
14853293  999  14852       0   [92]

[14853294 rows x 4 columns]

In [22]:
oralcke_globo.item.nunique()

14853

In [2]:
from dynamicTasteDistortion.dataset_loader import get_globo_df

In [4]:
globo_df = get_globo_df(1_000_000)

Skipping: 'dynamicTasteDistortion/data/globo' already exists and contains files.
Download finished! Merging intermediate files.

Processing files...: 100%|██████████| 385/385 [00:40<00:00,  9.51it/s]

Enriching globo.com dataset with k=3 random negative samples, due to implcit feedback

Processing users...: 100%|██████████| 331630/331630 [00:00<00:00, 942085.38it/s]

In [7]:
embs = pd.read_pickle("dynamicTasteDistortion/data/globo/articles_embeddings.pickle")

In [9]:
embs.shape

(364047, 250)

In [8]:
globo_df[globo_df["rating"] == 1]

           user    item      timestamp  rating  genres
0             1  235840  1506827017951       1     375
1             1   96663  1506827047951       1     209
2             3  236065  1506827536942       1     375
3             3  236294  1506827566942       1     375
4             5  168868  1506826884885       1     297
...         ...     ...            ...     ...     ...
1977421   34979  157478  1508211974116       1     281
1977422   10051  211442  1508211527302       1     340
1977423   10051   84911  1508211557302       1     174
1977424  123718  234481  1508211513583       1     375
1977425  123718  233578  1508211543583       1     375

[1977426 rows x 5 columns]

In [10]:
globo_df['genres'].iloc[0]

375

In [6]:
globo_df.item.nunique()

31227

In [9]:
globo_df.sample(1_000_000)

            user    item      timestamp  rating  genres
10682061   10451  249572  1507984563393       0     388
11473992  167697  224319  1508163497187       0     354
8640756    17406  102985  1507671420109       0     228
1385212   154523  244690  1507719435272       1     385
9769320   181074   37063  1507821715318       0      48
...          ...     ...            ...     ...     ...
3650513    46873  224354  1507041351636       0     354
11473341   47593   96663  1508165371044       0     209
6225835    14139  193902  1507350386585       0     317
6801691    32254   20287  1507488513367       0       9
2722327    50506  237224  1506959769912       0     375

[1000000 rows x 5 columns]

In [ ]:
# # 50% percentile
# globo_articles = globo_articles[globo_arti cles.groupby("category_id")["category_id"].transform("size") > 36]

In [ ]:
# globo_df = final_dataset.merge(globo_articles, on="article_id")
# # Remove users with less than 10 interactions
# globo_df = globo_df[globo_df.groupby("userId")["userId"].transform("size") > 10]

In [ ]:
# # Every entry has timestamp information
# globo_df[globo_df["timestamp"].isnull()]

Empty DataFrame
Columns: [userId, article_id, timestamp, category_id]
Index: []

In [ ]:
# # Keep only categories with more than 30 interactions (25% perrcentile in globo df before)
# globo_df = globo_df[globo_df.groupby("category_id")["category_id"].transform("size") > 30]

## CIT data

In [19]:
articles_cit = pd.read_csv("cit_news/shared_articles.csv")

In [21]:
articles_cit[articles_cit["lang"] == "pt"]

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang
10,1459210504,CONTENT SHARED,-9157338616628196758,5206835909720479405,-7864441319395545950,NaN,NaN,NaN,HTML,http://economia.ig.com.br/2016-03-27/situacao-...,Situação financeira ruim de varejistas pressio...,A queda nas vendas e a deterioração na situaçã...,pt
16,1459248366,CONTENT SHARED,-5917314377186856799,4670267857749552625,-265833983523746108,NaN,NaN,NaN,HTML,http://www.senar.org.br/agricultura-precisao/a...,Artigos e Palestras - Programa Agricultura de ...,Artigos e Palestras ARTIGOS / 2015 12/08/2015 ...,pt
17,1459248432,CONTENT SHARED,6157037646878010131,4670267857749552625,-265833983523746108,NaN,NaN,NaN,HTML,https://www.macroprograma1.cnptia.embrapa.br/r...,Rede Agricultura de Precisão II,Do Se Te Qu Qu Se Sa 27 28 29 30 31 Faça downl...,pt
21,1459251851,CONTENT SHARED,-1672166631728511207,4340306774493623681,-7292854281461484137,NaN,NaN,NaN,HTML,https://www.coinbr.net/blog/america-latina-apr...,O potencial do bitcoin na América Latina,28/03/2016 | por Safiri Felix | em Economia As...,pt
23,1459257477,CONTENT SHARED,5714314286511882372,1895326251577378793,6290959012079283980,NaN,NaN,NaN,HTML,https://www.sympla.com.br/como-startups-e-gran...,Como Startups e Grandes Empresas podem colabor...,Muito tem se falado sobre como grandes empresa...,pt
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3107,1487608245,CONTENT SHARED,-7264217791213422584,6013226412048763966,7817933231113759598,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR,HTML,http://vocerh.uol.com.br/noticias/legislacao/q...,Qual é o valor da área de T&D na sua empresa?,É fundamental que o departamento de Recursos H...,pt
3108,1487608319,CONTENT SHARED,-2402288292108892893,-4465926797008424436,-8412615285329455721,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR,HTML,http://www.codeatest.com/como-testar-excecoes-...,Como testar exceções em Java com o JUnit - Cod...,Introdução Neste post vou mostrar de forma suc...,pt
3109,1487616054,CONTENT SHARED,-624901815223005993,3609194402293569455,-2941135241517914970,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,SP,BR,HTML,https://googlediscovery.com/2017/02/20/i-duet-...,"A.I. Duet, crie melodias usando o aprendizado ...","O Google lançou o AI Duet , um novo experiment...",pt
3111,1487692411,CONTENT SHARED,-8591127493017117985,3609194402293569455,7126320888094993255,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,SP,BR,HTML,https://startupi.com.br/2017/02/ibm-e-visa-tra...,"IBM e Visa transformam automóveis, eletrodomés...",A IBM e a Visa anunciaram a primeira colaboraç...,pt
3117,1487946604,CONTENT SHARED,9213260650272029784,3609194402293569455,7144190892417579456,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,SP,BR,HTML,https://startupi.com.br/2017/02/liga-ventures-...,"Conheça a Liga IoT, plataforma de inovação abe...","A Liga Ventures, aceleradora de startups espec...",pt