In [7]:
from dynamicTasteDistortion.dataset_loader import read_ml_raw,  read_yelp_raw, process_ml_df, process_df
from dynamicTasteDistortion.scripts.data_utils import preprocess_genres
import pandas as pd

## Base datasets

In [9]:
ml_1m = read_ml_raw("s")

Skipping: 'dynamicTasteDistortion/data/movielens/raw/ml_s/' already exists and contains files.
Joining movies data with ratings data...

In [10]:
ml_1m_cleaned = process_ml_df(ml_1m)

Preprocessing dataset...

In [12]:
yelp = read_yelp_raw(1_000_000)

Downloading file...
Criando o diretorio dynamicTasteDistortion/data/yelp/raw/yelp_1000000/
Downloading...

Unzipping...

In [16]:
yelp_cleaned = process_df(yelp)

Preprocessing dataset...

In [17]:
yelp_cleaned

,user,item,rating,date,genres,binarized_rating,timestamp
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,2018-07-07 22:09:11,"Restaurants, Breakfast & Brunch, Food, Juice B...",0,1531001351
1,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,2014-02-05 20:30:30,"Restaurants, Breakfast & Brunch",0,1391632230
2,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,2017-01-14 20:54:15,"Sandwiches, Beer, Wine & Spirits, Bars, Food, ...",1,1484427255
3,r3zeYsv1XFBRA4dJpL78cw,gmjsEdUsKpj9Xxu6pdjH0g,5.0,2015-01-03 23:21:18,"Supernatural Readings, Tours, Hotels & Travel,...",1,1420327278
4,1WHRWwQmZOZDAhp2Qyny4g,uMvVYRgGNXf5boolA9HXTw,5.0,2015-06-21 14:48:06,"Shopping, Jewelry",1,1434898086
...,...,...,...,...,...,...,...
465282,RypZ2P165GB_igLo2JXw9Q,lnEeMas32ddqNn06jOUGgQ,1.0,2018-04-21 22:16:51,"Hotels, Hotels & Travel, Event Planning & Serv...",0,1524349011
465283,HBC6FIBHxo40h01tNhxn2g,fp7IHO1z53wYP4PzKSl11g,3.0,2011-11-13 21:35:09,"Food, Specialty Food, Korean, Chinese, Ethnic ...",0,1321220109
465284,i6L9I8xDF-di3kgvDewnjg,efGqAYPCCxPvHPX3dCM8bQ,5.0,2015-02-22 22:53:08,"Arts & Entertainment, Music Venues, Nightlife,...",1,1424645588
465285,oX7o1TH0PHUWp9r9ry9_vw,jLn69WQupjsDKrbPw_nlGQ,3.0,2017-11-15 09:43:07,"Ice Cream & Frozen Yogurt, Food",0,1510738987
465286,HYmGwYXvcYmW7dDjuWKJfw,54vEFcAri3Wj6cdM4ljDBA,4.0,2012-11-05 03:25:02,"Hotels, Hotels & Travel, Event Planning & Serv...",1,1352085902

In [18]:
yelp_cleaned["genres"] = preprocess_genres(yelp_cleaned, "genres", SEP=",")

In [ ]:
ml_1m

         item                       genres  user  rating   timestamp
0           1  Animation|Children's|Comedy     1       5   978824268
1           1  Animation|Children's|Comedy     6       4   978237008
2           1  Animation|Children's|Comedy     8       4   978233496
3           1  Animation|Children's|Comedy     9       5   978225952
4           1  Animation|Children's|Comedy    10       5   978226474
...       ...                          ...   ...     ...         ...
1000204  3952               Drama|Thriller  5812       4   992072099
1000205  3952               Drama|Thriller  5831       3   986223125
1000206  3952               Drama|Thriller  5837       4  1011902656
1000207  3952               Drama|Thriller  5927       1   979852537
1000208  3952               Drama|Thriller  5998       4  1001781044

[1000209 rows x 5 columns]

In [21]:
# Number of users, items, unique genres for ml_1m
num_users_ml = ml_1m['user'].nunique()
num_items_ml = ml_1m['item'].nunique()
unique_genres_ml = set(g for genres in ml_1m['genres'] for g in genres)
num_genres_ml = len(unique_genres_ml)

# Number of users, items, unique genres for yelp
num_users_yelp = yelp['user'].nunique()
num_items_yelp = yelp['item'].nunique()
unique_genres_yelp = set(g for genres in yelp_cleaned['genres'] for g in genres)
num_genres_yelp = len(unique_genres_yelp)


# ML-1M sparsity
ml_possible = num_users_ml * num_items_ml
ml_observed = len(ml_1m)
ml_sparsity = 1 - (ml_observed / ml_possible)

# Yelp sparsity
yelp_possible = num_users_yelp * num_items_yelp
yelp_observed = len(yelp)
yelp_sparsity = 1 - (yelp_observed / yelp_possible)

print("ML-1M: sparsity =", ml_sparsity)
print("Yelp: sparsity =", yelp_sparsity)


print("ML-1M: users =", num_users_ml, ", items =", num_items_ml, ", genres =", num_genres_ml)
print("Yelp: users =", num_users_yelp, ", items =", num_items_yelp, ", genres =", num_genres_yelp)

ML-1M: sparsity = 0.9553163743776871
Yelp: sparsity = 0.9998598761598543
ML-1M: users = 6040 , items = 3706 , genres = 30
Yelp: users = 136356 , items = 24352 , genres = 1149

In [22]:
# Number of users, items, unique genres for ml_1m
num_users_ml = ml_1m_cleaned['user'].nunique()
num_items_ml = ml_1m_cleaned['item'].nunique()
unique_genres_ml = set(g for genres in ml_1m_cleaned['genres'] for g in genres)
num_genres_ml = len(unique_genres_ml)

# Number of users, items, unique genres for yelp
num_users_yelp = yelp_cleaned['user'].nunique()
num_items_yelp = yelp_cleaned['item'].nunique()
unique_genres_yelp = set(g for genres in yelp_cleaned['genres'] for g in genres)
num_genres_yelp = len(unique_genres_yelp)


# ML-1M sparsity
ml_possible = num_users_ml * num_items_ml
ml_observed = len(ml_1m_cleaned)
ml_sparsity = 1 - (ml_observed / ml_possible)

# Yelp sparsity
yelp_possible = num_users_yelp * num_items_yelp
yelp_observed = len(yelp_cleaned)
yelp_sparsity = 1 - (yelp_observed / yelp_possible)

print("ML-1M: sparsity =", ml_sparsity)
print("Yelp: sparsity =", yelp_sparsity)


print("ML-1M: users =", num_users_ml, ", items =", num_items_ml, ", genres =", num_genres_ml)
print("Yelp: users =", num_users_yelp, ", items =", num_items_yelp, ", genres =", num_genres_yelp)

ML-1M: sparsity = 0.9498308751208008
Yelp: sparsity = 0.9998598294908749
ML-1M: users = 5289 , items = 3701 , genres = 18
Yelp: users = 136351 , items = 24344 , genres = 1149

In [ ]:
# Number of users, items, unique genres for ml_1m
num_users_ml = ml_1m['user'].nunique()
num_items_ml = ml_1m['item'].nunique()
unique_genres_ml = set(g for genres in ml_1m['genres'] for g in genres)
num_genres_ml = len(unique_genres_ml)

# Number of users, items, unique genres for yelp
num_users_yelp = yelp['user'].nunique()
num_items_yelp = yelp['item'].nunique()
unique_genres_yelp = set(g for genres in yelp['genres'] for g in genres)
num_genres_yelp = len(unique_genres_yelp)

print("ML-1M: users =", num_users_ml, ", items =", num_items_ml, ", genres =", num_genres_ml)
print("Yelp: users =", num_users_yelp, ", items =", num_items_yelp, ", genres =", num_genres_yelp)